class LoginForm extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.options = (this.getAttribute('options') || 'local').split(',');
    this.theme = this.getAttribute('theme') || 'light';
    this.dialogTitle = this.getAttribute('dialog-title') || 'Sign in';
    this.autoClose = this.hasAttribute('auto-close');
  }

  connectedCallback() {
    this.render();
  }

  render() {
    this.shadowRoot.innerHTML = `      
      <style>
        .error { color: red; font-size: 0.9em; }
        .loading { display: flex; align-items: center; gap: 0.5rem; }
      </style>
      <sl-dialog label="${this.dialogTitle}" open>
        <div style="display: flex; flex-direction: column; gap: 1rem;">
          ${this.options.includes('local') ? this.renderLocalLogin() : ''}
          ${this.renderProviderButtons()}
          ${this.options.includes('guest') ? this.renderGuestLogin() : ''}
          ${this.options.includes('signup') ? this.renderSignupToggle() : ''}
          <div id="error" class="error"></div>
        </div>
      </sl-dialog>
    `;

    this.shadowRoot.querySelector('#local-login-btn')?.addEventListener('click', () => this.handleLocalLogin());
    this.shadowRoot.querySelector('#guest-btn')?.addEventListener('click', () => this.emitLogin('guest'));
    this.shadowRoot.querySelector('#signup-toggle')?.addEventListener('click', () => this.toggleSignup());

    this.options.forEach(provider => {
      const btn = this.shadowRoot.querySelector(`#${provider}-btn`);
      if (btn) {
        btn.addEventListener('click', () => this.handleProviderLogin(provider));
      }
    });
  }

  handleLocalLogin() {
    const username = this.shadowRoot.querySelector('#username').value;
    const password = this.shadowRoot.querySelector('#password').value;
    const errorEl = this.shadowRoot.querySelector('#error');

    if (!username || !password) {
      errorEl.textContent = 'Username and password are required.';
      return;
    }

    this.setLoading(true);
    setTimeout(() => {
      this.emitLogin('local', { username, password });
      this.setLoading(false);
    }, 1000); // simulate async
  }

//   handleProviderLogin(provider) {
//     this.setLoading(true);
//     // this.handleProviderLogin(provider);
//     // setTimeout(() => {
//     //   this.emitLogin(provider, { token: null }); // token can be handled externally
//     //   this.setLoading(false);
//     // }, 1000);
//   }

  emitLogin(provider, detail = {}) {
    this.dispatchEvent(new CustomEvent('login-success', {
      detail: { provider, ...detail },
      bubbles: true,
      composed: true
    }));

    if (this.autoClose) {
      this.shadowRoot.querySelector('sl-dialog').hide();
    }
  }

  setLoading(isLoading) {
    const errorEl = this.shadowRoot.querySelector('#error');
    errorEl.textContent = '';
    if (isLoading) {
      errorEl.innerHTML = `<div class="loading"><sl-spinner></sl-spinner> Authenticating...</div>`;
    } else {
      errorEl.innerHTML = '';
    }
  }

  toggleSignup() {
    const dialog = this.shadowRoot.querySelector('sl-dialog');
    dialog.label = dialog.label.includes('Sign up') ? this.dialogTitle : 'Sign up';
  }

  renderLocalLogin() {
    return `
      <sl-input id="username" label="Username"></sl-input>
      <sl-input id="password" type="password" label="Password"></sl-input>
      <sl-button id="local-login-btn" variant="primary">Login</sl-button>
    `;
  }

  renderProviderButtons() {
    const icons = {
      google: 'google',
      facebook: 'facebook',
      linkedin: 'linkedin',
      apple: 'apple',
      microsoft: 'windows'
    };

    return this.options
      .filter(opt => !['local', 'guest', 'signup'].includes(opt))
      .map(opt => `
        <sl-button id="${opt}-btn" variant="default" size="medium">
          <sl-icon name="${icons[opt] || 'person'}" slot="prefix"></sl-icon>
          Continue with ${opt.charAt(0).toUpperCase() + opt.slice(1)}
        </sl-button>
      `).join('');
  }

  renderGuestLogin() {
    return `
      <sl-button id="guest-btn" variant="text">Continue as Guest</sl-button>
    `;
  }

  renderSignupToggle() {
    return `
      <sl-button id="signup-toggle" variant="text">Sign up</sl-button>
    `;
  }

  async handleProviderLogin(provider) {
    this.setLoading(true);
    try {
        const token = await this.startOAuthFlow(provider); // real login logic
        // this.emitLogin(provider, { token });
    } catch (err) {
        //this.showError(`Login with ${provider} failed.`);
        console.error(err);
    } finally {
        this.setLoading(false);
    }
    }


startOAuthFlow(provider) {
  // Return a Promise so the caller can await success or failure
  return new Promise((resolve, reject) => {

    // 1. Open a popup window to start the OAuth flow
    //    The URL is generated by getOAuthUrl(provider)
    const popup = window.open(this.getOAuthUrl(provider), '_blank', 'width=500,height=600');


    let handled = false;
    // 2. Define a handler for messages sent back from the popup
    const messageHandler = (event) => {
      // When the popup sends "google-login-success"
    if (event.data === 'google-login-success' && !handled) {
      handled = true;        
    // Remove the event listener so it doesn't fire multiple times
        window.removeEventListener('message', messageHandler);

        // Close the popup window (user has finished login)
        // popup.close(); //replaced with window.close(); in login.php server side

        // 3. Do a background session check with your backend
        //    This fetch call goes to session-check.php
        //    credentials: 'include' ensures cookies are sent
        fetch('https://php.adapps.download/api/session-check.php', {
            method: 'GET',
            credentials: 'include' // 🔑 required for cross-domain cookies
        })
          .then(res => res.json()) // Parse JSON response
          .then(data => {
            // If backend confirms user is logged in
            if (data.loggedIn) {
              // Emit a custom event with user info (email, userId)
              this.emitLogin(provider, {
                email: data.email,
                userId: data.userId
              });
              // Resolve the Promise with the data
              resolve(data);
            } else {
              // If backend says not logged in, reject the Promise
              reject('Session check failed');
            }
          })
          // Catch any network or parsing errors
          .catch(err => reject(err));
      }
    };

    // 4. Attach the message handler to listen for postMessage from popup
    window.addEventListener('message', messageHandler);

    // ✅ Poll for popup closure
    const checkClosed = setInterval(() => {
        if (popup.closed && !handled) {
        handled = true;
        clearInterval(checkClosed);
        window.removeEventListener('message', messageHandler);
        this.setLoading(false); // hide "Authenticating..."
        // reject('Popup closed without login');
        console.warn('Login popup was closed by the user.');
      }
    }, 500);
  });
}

    getOAuthUrl(provider) {
        const clientId = '842799415320-ujd4fodvctbgrc6jdfkb596opkiva859.apps.googleusercontent.com';
        const redirectUri = 'https://php.adapps.download/api/login.php';
        const scope = 'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/userinfo.email';
        const state = crypto.randomUUID(); // optional but recommended

        return `https://accounts.google.com/o/oauth2/v2/auth?client_id=${clientId}&redirect_uri=${redirectUri}&response_type=code&scope=${encodeURIComponent(scope)}&access_type=offline&state=${state}`;
    }


}

customElements.define('login-form', LoginForm);